// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    gettingStartedSidebar: [{
        type: 'autogenerated',
        dirName: '.'
    }],
};

export default sidebars;
